# Generated by Django 5.2.17 on 2026-09-30 19:22

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgerecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='kb_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
